## Importing Libraries

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import statistics
import numpy as np
import sys
import math
np.set_printoptions(threshold=sys.maxsize)

## Reading Data from File

In [3]:
#Reading data from ex1data1.txt file
data=pd.read_csv('ex1data2.txt', header=None, names=["Area","BedRooms","Price"])

## Calculating Mean/Standard Daviation

In [39]:
rows=data.shape[0]

cols=len(data.columns)

X2=data.iloc[:,:cols-1]
Y2=data.iloc[:,cols-1]

area=data.iloc[:,0]
beds=data.iloc[:,1]
price=data.iloc[:,2]

areaMean=statistics.mean(area)
bedsMean=statistics.mean(beds)
priceMean=statistics.mean(price)

areaSTDev=statistics.stdev(area)
bedsSTDev=statistics.stdev(beds)
priceSTDev=statistics.stdev(price)

## Applying Normalization

In [5]:
for i in range(rows):
    data.iloc[i,0]=(data.iloc[i,0]-areaMean)/areaSTDev
    data.iloc[i,1]=(data.iloc[i,1]-bedsMean)/bedsSTDev
    data.iloc[i,2]=(data.iloc[i,2]-priceMean)/priceSTDev

## Initializing Data

In [17]:
thetas=[[ 0 for i in range(cols)]]

thetas=np.transpose(thetas)

print(thetas)

matrix=data.to_numpy()

X=np.ones((rows,cols))
Y=np.ones((rows,1))

X[:,1:]=matrix[:,:(cols-1)]
Y[:,0]=matrix[:,-1]

[[0]
 [0]
 [0]]


## Running Iterations

In [36]:
alpha=0.001

print(thetas[0].shape)

for i in range(500):
    
    f1=np.transpose(np.subtract(np.dot(X,thetas),Y))
    f2=np.subtract(np.dot(X,thetas),Y)
    f3=np.dot(f1,f2)

    cost=(1/(2*rows))*f3
    
    print("Iteration #:",i)
    print(cost)
    
    for m in range(cols):
        thetas[m][0]=thetas[m][0]-((alpha/rows)*cost)
    
    print(thetas)

(1,)
Iteration #: 0
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 1
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 2
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 3
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 4
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 5
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 6
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 7
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 8
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 9
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 10
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 11
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 12
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 13
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 14
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 15
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 16
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 17
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 18
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 19
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 20
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 21
[[0.4893617]]
[[0]
 [0]

Iteration #: 347
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 348
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 349
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 350
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 351
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 352
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 353
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 354
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 355
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 356
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 357
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 358
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 359
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 360
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 361
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 362
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 363
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 364
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 365
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 366
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 367
[[0.4893617]]
[[0]
 [0]
 [0]]
Iteration #: 

## Using Normal Equations

In [ ]:

x_transpose = np.transpose(X2)
thetas=np.linalg.pinv(x_transpose*X2)*x_transpose*Y2

print(thetas)